# Generated by Django 4.1.7 on 2023-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTimout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_uid', models.CharField(max_length=25)),
                ('hash', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
