# Generated by Django 4.1.7 on 2023-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetimout',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeetimout',
            name='employee_uid',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
